spring:
  application:
    name: demo-ws
  profiles:
    active: dev

server:
  port: ${SERVER_PORT:8888}

jwt:
  secret: ${JWT_SECRET:7D8F3CFA04C2998E27A5EABF8D1F99C6A2B1C38FBA94E6236F62C4A45B9A9E35A33E84F822EF47C63B5C9F47EDAA6BFC}
  expiration: ${JWT_EXPIRATION_MS:604800000}

websocket:
  allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS:*}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  server-url: ${OPENAPI_SERVER_URL}

logging:
  level:
    org.example.demows: INFO
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
