spring:
  application:
    name: demo-ws

  # Keep base file lean; override in application-<profile>.yml via env vars
  profiles:
    active: dev

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:CHANGE_ME_DEV_ONLY}
  expiration: ${JWT_EXPIRATION_MS:86400000}

websocket:
  allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  server-url: ${OPENAPI_SERVER_URL:}

logging:
  level:
    org.example.demows: INFO
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
