spring:
  application:
    name: demo-ws
  kafka:
    bootstrap-servers: pkc-921jm.us-east-2.aws.confluent.cloud:9092
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="TFMDAW74HQDVKMBB" password="cfltFnSLKywHDBKqTPTxwLugQQfTjvrfpF6jSi2+AgnXvGbS4+uPemwV2PbVPDNw";'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: demo-ws-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:postgresql://34.143.160.47:54111/demo-ws
    username: demo-ws
    password: demo-ws
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false


# Server Configuration
server:
  port: 8080

# JWT Configuration
jwt:
  secret: 7D8F3CFA04C2998E27A5EABF8D1F99C6A2B1C38FBA94E6236F62C4A45B9A9E35A33E84F822EF47C63B5C9F47EDAA6BFC
  expiration: 86400000

# WebSocket Configuration
websocket:
  allowed-origins: ""

# Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  servers:
    - url: https://demo-websocket-production.up.railway.app
      description: Production server

# Logging Configuration
logging:
  level:
    org.example.demows: DEBUG
    org.springframework.security: DEBUG
    org.springframework.kafka: DEBUG
    org.apache.kafka.clients.NetworkClient: DEBUG
    org.apache.kafka.clients.Metadata: DEBUG

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
